[build]
  command = "npm run build"
  functions = "out_functions"
  publish = "out_publish"

[functions]
  directory = "out_functions"

[dev]
  functions = "out_functions"
  publish = "out_publish"
  # We manually set the framework to static, otherwise Netlify automatically
  # detects Next.js and redirects do not work.
  # Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  framework = "#static"
